
INSERT INTO `quiz_questions` (`question`,`option_a`,`option_b`,`option_c`,`option_d`,`correct`,`tags`) VALUES
('Za šta stoji skraćenica HTML?','HyperText Markup Language','Home Tool Markup Language','Hyperlinks and Text Markup Language',NULL,'a','html,basics'),
('Koji tag kreira paragraf?','<p>','<para>','<text>',NULL,'a','html,element'),
('Koji atribut se koristi za alternativni tekst slike?','alt','title','src',NULL,'a','html,attributes'),
('Koji tag se koristi za uređeni (numerisan) popis?','<ol>','<ul>','<li>',NULL,'a','html,lists'),
('Kako povežete eksterni CSS fajl?','<link rel="stylesheet" href="styles.css">','<script src="styles.css"></script>','<css src="styles.css">',NULL,'a','css,linking'),
('Koja osobina mijenja boju teksta u CSS-u?','color','text-color','font-color',NULL,'a','css,properties'),
('Kako selektujete element sa id "main" u CSS-u?','#main','.main','main',NULL,'a','css,selectors'),
('Koja osobina kontroliše razmak između redova teksta?','line-height','letter-spacing','word-spacing',NULL,'a','css,typography'),
('Koji HTML element definiše zaglavlje dokumenta ili sekcije?','<header>','<head>','<h1>',NULL,'a','html,semantic'),
('Koji tag se koristi za prelom reda?','<br>','<break>','<lb>',NULL,'a','html,element'),
('Koji je ispravan način za umetanje pozadinske slike?','use CSS background-image','<bg>','<background>',NULL,'a','html,css'),
('Kako se piše komentar u HTML-u?','<!-- comment -->','// comment','/* comment */',NULL,'a','html,syntax'),
('Koja CSS osobina se koristi za promjenu veličine fonta?','font-size','text-size','font-style',NULL,'a','css,properties'),
('Koja osobina se koristi za promjenu boje pozadine?','background-color','bgcolor','color',NULL,'a','css,properties'),
('Kako napraviti listu sa bullet tačkama?','<ul>','<ol>','<list>',NULL,'a','html,lists'),
('Koji tag se koristi za red u tabeli?','<tr>','<td>','<th>',NULL,'a','html,tables'),
('Koji atribut se koristi za destinaciju linka?','href','src','link',NULL,'a','html,attributes'),
('Koja CSS osobina čini tekst podebljanim?','font-weight','font-style','text-weight',NULL,'a','css,typography'),
('Koji je ispravan HTML za dodavanje boje pozadine?','<body style="background-color:yellow;">','<body bg="yellow">','<background>yellow</background>',NULL,'a','html,inline-css'),
('Kako centrirati element horizontalno koristeći CSS?','margin: 0 auto;','text-align:center;','align:center;',NULL,'a','css,layout'),
('Koja CSS osobina kontroliše širinu elementa?','width','size','length',NULL,'a','css,layout'),
('Koji HTML element definiše naslov dokumenta prikazan u tabu preglednika?','<title>','<head>','<meta>',NULL,'a','html,head'),
('Kako napraviti tekst kurzivnim u HTML-u?','<em> or <i>','<italic>','<it>',NULL,'a','html,formatting'),
('Koji CSS selektor bira element po klasi?','.class','#class','class',NULL,'a','css,selectors'),
('Koji HTML5 element se koristi za navigacione linkove?','<nav>','<navigation>','<menu>',NULL,'a','html,semantic'),
('Kako uključiti JavaScript u HTML?','<script src="app.js"></script>','<js src="app.js"></js>','<include src="app.js">',NULL,'a','html,script'),
('Koji atribut je potreban za responzivni meta tag?','viewport','responsive','mobile',NULL,'a','html,meta'),
('Koja osobina postavlja razmak između sadržaja i obruba (padding)?','padding','margin','spacing',NULL,'a','css,box-model'),
('Koja osobina postavlja prostor izvan elementa (margin)?','margin','padding','border',NULL,'a','css,box-model'),
('Kako se piše komentar u CSS-u?','/* comment */','// comment','<!-- comment -->',NULL,'a','css,syntax'),
('Koja jedinica je relativna u odnosu na veličinu fonta root elementa?','rem','em','px',NULL,'a','css,units'),
('Koji HTML atribut definiše inline stilove?','style','class','id',NULL,'a','html,attributes'),
('Šta svojstvo box-sizing kontroliše u CSS-u?','how width/height are calculated','element box shadow','border radius',NULL,'a','css,box-model'),
('Koja osobina određuje redoslijed flex elemenata?','order','flex-order','position',NULL,'a','css,flexbox'),
('Kako napraviti element nevidljiv ali da zauzima prostor?','visibility:hidden','display:none','opacity:0',NULL,'a','css,visibility'),
('Koji HTML element je namijenjen za samostalan sadržaj koji se može distribuirati odvojeno?','<article>','<section>','<div>',NULL,'a','html,semantic'),
('Koji tag označava najveći naslov?','<h1>','<h6>','<header>',NULL,'a','html,headings'),
('Koja CSS osobina dodaje zaobljene uglove?','border-radius','corner-radius','radius',NULL,'a','css,properties'),
('Koja pseudo-klasa cilja prvog potomka roditelja?',':first-child',':first',':child-first',NULL,'a','css,pseudo'),
('Koji HTML atribut omogućava otvaranje linka u novom tabu?','target="_blank"','rel="external"','open="new"',NULL,'a','html,attributes'),
('Koja osobina kreira fleksibilan model rasporeda?','display:flex','float:left','position:relative',NULL,'a','css,flexbox'),
('Kako napraviti grid raspored?','display:grid','display:flexbox','grid-layout',NULL,'a','css,grid'),
('Koja osobina kontroliše preljevanje sadržaja (overflow)?','overflow','text-overflow','clip',NULL,'a','css,layout'),
('Koji HTML element predstavlja glavni sadržaj dokumenta?','<main>','<section>','<div>',NULL,'a','html,semantic'),
('Koji CSS skraćeni zapis postavlja padding na svim stranama?','padding: 10px;','padding-top:10px;','padding-all:10px;',NULL,'a','css,shorthand'),
('Kako primijeniti CSS samo za ekrane sa maksimalnom širinom 600px?','@media (max-width: 600px) { ... }','@responsive max-width 600px','@screen 600px { ... }',NULL,'a','css,responsive'),
('Koji atribut daje alternativni tekst za pristupačnost kod slika?','alt','title','aria-label',NULL,'a','html,accessibility'),
('Koji element se koristi za grupisanje kontrola forme?','<form>','<fieldset>','<group>',NULL,'b','html,forms'),
('Koja osobina mijenja providnost elementa (opacity)?','opacity','visibility','display',NULL,'a','css,properties'),
('Koji HTML element se koristi za citirani odlomak?','<blockquote>','<quote>','<q>',NULL,'a','html,semantics'),
('Koja CSS osobina stvara stacking context?','z-index','stack','order',NULL,'a','css,stacking');
